### ISSUE TITLE
wont build Mac

### ISSUE THREAD

**Issue by worthbeer** [EliEladElrom/cra-template-must-have-libraries#4]
error pretty-format@27.0.6: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0". Got "14.6.0"
error Found incompatible module.

build aborts then reverts, 
Mac 11.2.2
node v14.6.0
yarn 1.22.5

**Comment by EliEladElrom** [comment]
Since this is not reproducible Github Action and Travis CI and I was able to build on Mac 11.4, node v14.17.0, yarn 1.22.10 without an issue.  This type of dependency issue is often machine-specific.  As we discussed, try to install each library one by one from the package.json file, until you see which one fails. Also uninstall and reinstall node, something along that line, removing old directories and such   Let me know.  For you know you could use the book chapter directories with --legacy-peer-deps.

**Comment by worthbeer** [comment]
node: 'v14.6.0', npm: '7.19.1'

it is the node version there are a host of warnings coming up with atempts to install jest opened  issue on node
https://github.com/nodejs/node/issues/39309

thanks
